-- Giai đoạn 2: lưu từ khóa thị trường, lịch sử quét và video tìm thấy.
-- Chạy toàn bộ file này một lần trong Supabase SQL Editor.

create table if not exists public.market_keywords (
  id bigint generated by default as identity primary key,
  keyword text not null,
  normalized_keyword text not null,
  subject text default '',
  niche text default '',
  region_code text default 'US',
  language_code text default 'en',
  video_type text default 'all' check (video_type in ('all', 'long', 'shorts')),
  period_days integer default 30 check (period_days > 0),
  result_limit integer default 24 check (result_limit between 1 and 50),
  scan_cycle text default 'manual',
  is_active boolean default true,
  last_scanned_at timestamptz,
  last_result_count integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now(),
  unique(normalized_keyword, region_code, language_code, video_type)
);

create table if not exists public.market_scans (
  id bigint generated by default as identity primary key,
  keyword_id bigint references public.market_keywords(id) on delete cascade,
  query text not null,
  normalized_query text not null,
  subject text default '',
  niche text default '',
  region_code text default 'US',
  language_code text default 'en',
  video_type text default 'all',
  period_days integer default 30,
  result_limit integer default 24,
  search_order text default 'viewCount',
  deep_channel_limit integer default 0,
  result_count integer default 0,
  total_views bigint default 0,
  average_views_per_day bigint default 0,
  unique_channels integer default 0,
  average_subscribers bigint default 0,
  api_units_estimated integer default 0,
  deep_channels_analyzed integer default 0,
  status text default 'success',
  error_message text default '',
  scanned_at timestamptz default now()
);

create index if not exists market_scans_keyword_idx
  on public.market_scans(keyword_id, scanned_at desc);
create index if not exists market_scans_query_idx
  on public.market_scans(normalized_query, region_code, language_code, scanned_at desc);

create table if not exists public.market_results (
  id bigint generated by default as identity primary key,
  scan_id bigint not null references public.market_scans(id) on delete cascade,
  keyword_id bigint references public.market_keywords(id) on delete cascade,
  source_keyword text not null,
  subject text default '',
  niche text default '',
  region_code text default 'US',
  language_code text default 'en',
  video_type text default 'long',
  video_id text not null,
  channel_id text not null,
  channel_title text default '',
  title text default '',
  published_at timestamptz,
  view_count bigint default 0,
  like_count bigint default 0,
  comment_count bigint default 0,
  duration text default '',
  duration_seconds integer default 0,
  thumbnail_url text default '',
  views_per_day bigint default 0,
  channel_subscriber_count bigint default 0,
  channel_total_view_count bigint default 0,
  channel_video_count bigint default 0,
  channel_country text default '',
  channel_thumbnail_url text default '',
  channel_published_at timestamptz,
  channel_uploads_playlist_id text default '',
  channel_baseline_views bigint default 0,
  baseline_video_count integer default 0,
  outlier_score numeric default 0,
  discovered_at timestamptz default now(),
  unique(scan_id, video_id)
);

create index if not exists market_results_scan_idx
  on public.market_results(scan_id, views_per_day desc);
create index if not exists market_results_keyword_idx
  on public.market_results(keyword_id, discovered_at desc);
create index if not exists market_results_video_idx
  on public.market_results(video_id, discovered_at desc);
create index if not exists market_results_channel_idx
  on public.market_results(channel_id, discovered_at desc);

alter table public.market_keywords enable row level security;
alter table public.market_scans enable row level security;
alter table public.market_results enable row level security;

-- Không cần policy khi Streamlit dùng SUPABASE_KEY dạng service_role.
